run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor
  exclude-files:
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - errorlint
        - errcheck
    - linters:
        - goconst
      source: "case \".*\":|return \".*\"|== \".*\""
    - linters:
        - staticcheck
      text: "SA1019.*deprecated"

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - errorlint
    - unconvert
    - goconst

linters-settings:
  goimports:
    local-prefixes: github.com/clawscli/claws
  gofmt:
    simplify: true
  goconst:
    min-len: 5
    min-occurrences: 5
